name: Feature
description: A change to how a sound zone is controlled
title: "Feature: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What should the integration do?
    validations:
      required: true
